POST http://localhost:5000/client
Content-Type: application/json

{
    "nom": "Mr Roland",
    "prenom": "",
    "email": "Nom@example.com",
    "telephone": "0777777777",
    "adresse": "lili"
}

###
GET http://localhost:5000/client

###
GET http://localhost:5000/client/3/commandes

###
PUT http://localhost:5000/client/3
Content-Type: application/json

{
    "nom": "Mr RollandModif",
    "prenom": "Prenodm",
    "email": "Nom@example.com",
    "telephone": "0777777778",
    "adresse": "37 rue de Montignon"
}

###
DELETE http://localhost:5000/client/4








###
POST http://localhost:5000/commande
Content-Type: application/json

{
"NumeroCommande": "CMDDDD12345",
"MontantTotal": 100.50,
"Statut": "Expédiée",
"ClientId": 4
}

###
GET http://localhost:5000/commande

###
GET http://localhost:5000/commande/4

###
PUT http://localhost:5000/commande/4
Content-Type: application/json

{
"NumeroCommande": "CMDDDD12345",
"MontantTotal": 100.50,
"Statut": "Livrée",
"ClientId": 3
}

###
DELETE http://localhost:5000/commande/5




